;Configuration data for Apollo Discovery SimSystem
[SimSys]
DataFormat=1
CreatedDate=30/05/2017
ModifiedDate=30/05/2017
PanelType="Unknown Panel"
[Loop1]
CableImpedance=1810
CableFirstRun=0
CableFirstLength=0
CableMaxRun=0
CableTotalLength=0
Calculation=0
MaxOutputs=126
DINLEDsDisabled=False
IgnoreIsolators=False
Device1=27
Device2=27
Device3=27
Device4=27
Device5=27
Device6=27
Device7=27
Device8=27
Device9=27
Device10=27
